FROM envoyproxy/envoy:v1.16.5

COPY ./server/envoy-proxy.yaml /etc/server-envoy-proxy.yaml
RUN chmod go+r /etc/server-envoy-proxy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/server-envoy-proxy.yaml", "--service-cluster", "backend-proxy"]
